### PR TITLE
Feat/add synapse fixes

### PR DESCRIPTION
**Pull request by merkata**
### Overview

Adds two bug fixes - throttling rate limit for bot users and a fix for the prometheus port on worker units.

### Rationale

Fixes from trunk, propagating to 1/ channels.

### Juju Events Changes

n/a

### Module Changes

n/a

### Library Changes

n/a

### Checklist

- [x ] The [charm style guide](https://juju.is/docs/sdk/styleguide) was applied
- [x ] The [contributing guide](https://github.com/canonical/is-charms-contributing-guide) was applied
- [x ] The changes are compliant with [ISD054 - Manging Charm Complexity](https://discourse.charmhub.io/t/specification-isd014-managing-charm-complexity/11619)
- [x ] The documentation is generated using `src-docs`
- [x ] The documentation for charmhub is updated.
- [x ] The PR is tagged with appropriate label (`urgent`, `trivial`, `complex`)

### CODE REVIEW

**Comment by amandahla** [comment]
You are also removing enable_irc_bridge here, right?

**Review by yanksyoon — COMMENTED** [review]
Out of curiosity, what bug does this fix and what does irc-bridge removal do in this case?

**Comment by merkata** [comment]
> You are also removing enable_irc_bridge here, right?

Yes, it had to be removed as some checks were failing, This was an effort to test the branching strategy, so I'm closing this one out.

**Comment by merkata** [comment]
> Out of curiosity, what bug does this fix and what does irc-bridge removal do in this case?

This PR is a test against the branching strategy. The irc code had to be removed for the fix to make it through, so we have to draw conclusions from that..I am closing this PR.

**Comment by merkata** [comment]
Closing.

**Pull request closed without merging**
