### PR TITLE
New issue templates for chat.ubuntu.com

### PR DESCRIPTION
**Pull request by kewisch**

### CODE REVIEW

**Comment by kewisch** [comment]
We'll need to adjust the labels on this repo to account for the new (and missing) ones.

**Comment by amandahla** [comment]
/canonical/self-hosted-runners/run-workflows f72a747

**Comment by gregory-schiano** [comment]
/canonical/self-hosted-runners/run-workflows ade08f38d833cd4e00432c33dd3dc30691756be2

**Comment by gregory-schiano** [comment]
`/canonical/self-hosted-runners/run-workflows ade08f38d833cd4e00432c33dd3dc30691756be2`

**Comment by amandahla** [comment]
While we work on this, I made the same changes here https://github.com/canonical/synapse-operator/pull/84 so I'm closing this one.

**Pull request closed without merging**
